### ISSUE TITLE
Indianapolis & Portland

### ISSUE THREAD

**Issue by DeclanEM** [YourWaifuIsShip/Azur-Lane-Guides#16]
I had a question / clarification re the guide.

Portland is listed as T0.5 ship while Indianapolis is listed as a T2. Considering that Indianapolis grants a bonus to Portland it's not entirely clear whether or not Portland's T0.5 listing is dependent on her skill being activated by Indianapolis. It might be worth adding a line to Portland's listing clarifying that.

**Comment by YourWaifuIsShip** [comment]
"Exceptional HP, twice the base Evasion other CAs get, good Firepower and high AA: in a similar fashion to Cleveland, her stats alone justify her rating and the skills are just window dressing, with the Indianapolis-related buff in particular being wholly irrelevant (as her sister is way too weak to be worth consideration).
She won't hit as often as Wichita or as hard as Chicago, but she's cheap, damn hard to kill and consistent."

That should do it, I believe~

**Comment by DeclanEM** [comment]
Sounds great! Thanks.
