### ISSUE TITLE
Double AA gear for Mikasa?

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#17]
I mean, she can’t even equip an AA gun to begin with.

I don’t get the reason why.

**Comment by guroteske** [comment]
anti-air stat reduces the damage received by planes that crash into your backline. if you're crazy enough to actually use mikasa for late-game maps (w12 and 13), you *need* to pad her aa stat as high as possible in order to not get shredded by enemy planes
