### ISSUE TITLE
Formidable loadout question 

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#18]
When you gear Formidable for a BOSS fleet, wouldn’t it make sense to put a divebomber in the first slot?

I see it makes her reload longer, but more damaging. Maybe even a BTD-1 instead of a Helldiver?

**Comment by YourWaifuIsShip** [comment]
Formidable's main source of damage are her 6 Torpedo Bombers (which should be Ryuusei), not her 2 Dive Bombers; the respective efficiencies are plane counts are noticeably lower and when you're thking of her F/D slot you shouldn't be thinking of damage in the first place, but of utility.

The best thing about Formidable is her ability to root+slow enemies for other backliners, torpcarriers in primis, to pound into smithereens with their aimed torpedoes; therefore you want to have her launch **last**, as the torpedo bombers take a little time to actually drop the payload and by the time she launches, they will have indeed launched.

As for the BTD-1, they're bad (considerably weaker and less accurate payload compared to the SB2C while being more expensive to raise) and there's no reason whatsoever to use them; you can see that by the wiki's own Dive Bomber charts, and this: https://github.com/guroteske/al-guides/blob/master/Equipment%20Guide.md
