### ISSUE TITLE
Description for San Juan's skill is wrong

### ISSUE THREAD

**Issue by Naurhir** [YourWaifuIsShip/Azur-Lane-Guides#21]
Your current version lacks the important 'Eagle Union' requirement for the buff.  You have two descriptions for her that point to the USS, but not in the skill that makes it matter.

Your wording: "Upon firing AA guns, 25% chance to grant +30% AA to ALL units in the fleet for 5s; also, every 13 main gun shots hits, gain a stack of +8% FP (max. 3 stacks)"

Wiki's wording: "When firing Anti-Air guns: 25% chance to increase Anti-Air for all Eagle Union ships by 15% (30%) for 5 seconds. When main gun shots hit 13 times: increases own Firepower by 3.5% (8%), effect can stack up to 3 times. "

**Comment by YourWaifuIsShip** [comment]
True enough, must've missed it during the migration. It's fixed now though, thanks for the heads-up~
