### ISSUE TITLE
Louis‘ gun for Bremerton?

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#23]
For other CA with a 5 second cooldown ability you noted not to use the Louis gun due to the fast reload.

Shouldn’t the same be true for Bremerton?

**Comment by YourWaifuIsShip** [comment]
There is still some uncertainty on the matter, last time we covered the subject the consensus semeed to be that the Louis Gun still worked except in some niche circumstances; still, better safe than sorry and I've talked in the past how the Type 3 tends to be more helpful on Gun-CAs anyway (+1 shot to deal with shields).
Thanks for spotting it~
