### ISSUE TITLE
Separated changelog

### ISSUE THREAD

**Issue by Zumochi** [YourWaifuIsShip/Azur-Lane-Guides#24]
May I suggest splitting the change log into a separate file? That way you can easily look back more historically when a ship got added/removed/moved and why.

Open to other ideas/thoughts!

**Comment by YourWaifuIsShip** [comment]
Not a bad idea actually, it could give some perspective when looking back on stuff... not something I'll add right now though, I'm having some personal issues draining my time, but something I'll probably do eventually.
Got any more suggestions, shoot~

**Comment by Zumochi** [comment]
Sorry for the late response :)

If you like, I can make a PR with how I would envision it?
