### ISSUE TITLE
VF17 versus Hellcat

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#25]
VF17 has T0 bombs, faster reload and a fleetwide buff.

Has the Hellcat been declassed now?

**Comment by YourWaifuIsShip** [comment]
Not until you can get enough to replace _every single one of them on your carriers_ c:
The F6Fs are still great, and should the VF17 AA (which is somewhat inferior, though not by much) not cut it, you will probably go back to them. Just make sure you use at least one VF17 in that case, the fleetwide AA boost is still very much welcome.
