### ISSUE TITLE
Missing Loadouts for Unicorn?

### ISSUE THREAD

**Issue by ramzh** [YourWaifuIsShip/Azur-Lane-Guides#26]
Seems like Unicorn is missing the loadouts, was that on purpose?

**Comment by ramzh** [comment]
Noticed that other ships are too

**Comment by YourWaifuIsShip** [comment]
Fixed Unicorn; sorry for not answering until now, I don't pay much attention to the Issues here (I much prefer Discord for this sort of thing).
The other loadouts missing will keep missing until I upgrade the Guide as a whole, or enough requests are made to add them in right now.
