### ISSUE TITLE
Specify what is the Azuma Gun

### ISSUE THREAD

**Issue by polcats** [YourWaifuIsShip/Azur-Lane-Guides#29]
I think it would be better to be more specific as to what is the "Azuma Gun" as not everyone knows this.

**Comment by YourWaifuIsShip** [comment]
Duly noted and added, thanks~
![Screenshot_1](https://user-images.githubusercontent.com/46425140/81969612-8901c000-961e-11ea-969c-6770b6bd7894.png)
