### ISSUE TITLE
Where is Victorious?

### ISSUE THREAD

**Issue by xfhnbr** [YourWaifuIsShip/Azur-Lane-Guides#30]

**Comment by EndlingGER** [comment]
While she doesn’t deserve to land in Untier (imho) don’t expect her to rank high.

She brings nothing to support her fleet (especially Formidable’s slow is in high demand).
All her stats are a tad lower than that of her sisters, except luck. Her reload isn’t just low, it’s the lowest of ALL carriers in game.

Her niche would be a against a BB boss, where her sister’s 6 Torp bombers and pretty much any BB/BC with an AP gun can perform at least just as good.

If her chance for double damage would be closer to that of Enterprise things were different...

**Comment by YourWaifuIsShip** [comment]
In the trash, that's where. Since you asked, I suppose I'll add her to the Untier Guide - that's generally how I add bad units in there, someone's got to ask first (as bad units are generally just ignored, after all).
