### ISSUE TITLE
Tierless guide opinion

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#31]
I do understand that trying to condense a ships “worth” on a single value can be difficult. Especially when people only look at the value without reading the description and wonder why things aren’t working out.

On the other hand I believe that there must be some kind of bar so we can gauge how far above or below a ship performs said bar. And in the end this is what many people seek, some metric(s) to compare ships an their qualities.

This might become problematic when you keep “inventing” roles. Not that it’s wrong to point out a ship’s advantages, but when you stick to the role system you would need to take things form the other end.

What roles do we need to beat 13/4, 10/4 hard or an Event’s SP stage? And what ships fit those? And how well do they perform in this roles? (Just3c made a video on late game fleet building not to long ago. He made some good remarks there)

There might of course be other roles, with some ships excelling in it, but is should be clear then that those roles do turn obsolete with progressing difficulty.

Maybe, instead of starting from scratch, it might be better to simply split up the single tier into a couple of values? For example:

a DPS ranking, how much damage a ship can do independently.
a SUPPORT ranking, how much a ship can increase the performance of the rest of the fleet.
a SURVIVABILITY ranking, how long can a ship keep herself and other fleetmates alive.
And, out of necessity, an AA ranking, how well they can handle plane hells.

This could help people understand why for example Unicorn ranks so high although her damage is only so so or why Eugen is on the brink of Untier although she can tank so much damage.

That’s what I think.

**Comment by YourWaifuIsShip** [comment]
It's an interesting suggestion, to be sure, but one I feel would cause more problems than it'd solve.

As you correctly pointed out, the main reason to attempting to ditch the tiers is to steer people away from the endless bickering about entirely arbitrary evaluations of relative goodness to have them focus on what matters instead, ie. what they do and how they do it; if I were to then give numbers to DPS/Tank/Sup I'd be creating *more* tiers that could be bickered about, and that runs counter to my original intent.

That said, once the dust settles and more opinions have been collected, I think I will give the Roles field more prominence and publish, perhaps in place of the Tier Explanations, their Explanations instead.

**Comment by paeter** [comment]
For me, I like the old “tier” system just as a guide to compare to other ships.

**Comment by EndlingGER** [comment]
> For me, I like the old “tier” system just as a guide to compare to other ships.

At the very end of the day, I don’t expect tierings to be gone for good.

Even if everything is role based, there is still a need to present who is the best for example Vanguard Main tank. That needs some kind of metric or rating.

The biggest plus is that players need to catch up on fleet composition and role is needed when and where.

**Comment by YourWaifuIsShip** [comment]
Refer to the more recent comments on these issues for an update on the 'situation'~
Closing this now since they're starting to pile up but don't worry, senpai noticed the objections and has thought of ways to work with them.
