### ISSUE TITLE
Tierless Feedback and Discord question

### ISSUE THREAD

**Issue by Sme4** [YourWaifuIsShip/Azur-Lane-Guides#34]
I also much prefer the 0-2 tier system. I have been using this guide since I started Azur Lane, and I use the tier system to build my late game fleets. I would like the tiers to stay. Also, I noticed that on a closed question, you said you prefer using discord as a way to receive feedback, but I do not see a way to contact you there unless I am missing it somewhere. If you accept discord feedback, then maybe make your discord more visible?

**Comment by YourWaifuIsShip** [comment]
![unknown](https://user-images.githubusercontent.com/46425140/83970757-b832e680-a8d7-11ea-96a7-8d386dae4b3d.png)
Right there in the readme~

The feedback has been rather contradictory so far, the Discord seems to prefer the tierless version and the comments here seem to prefer, if not the tiers, at least some numbers to gauge at a glance.
For now, I'll refine the Tierless version and see if something can be found to meet both camps halfway.

**Comment by RHagoort** [comment]
I don't have discord, so wil leave feedback here: I love the tiered guides and use them a lot. I'm no fan of the untiered appoach.
