### ISSUE TITLE
About the latest change

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#36]
Did you intentionally weed out most of the tier 2 CA?

And will you do similar with the other ship types?

**Comment by YourWaifuIsShip** [comment]
Most? Only a few were cut off, some of them being shunted over to the Early Recommendations (and some, like the Hippers, being cut off entirely because they were bad).
More could be cut, we'll see in time; I'll mention it more clearly in the changelog, since I forgot to do so this time around.

**Comment by EndlingGER** [comment]
Sorry, I hadn’t seen your change in the early recommendations. Guess I was sour that Maya had to be ditched.
