### ISSUE TITLE
Magnetic torpedoes 

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#38]
Most sources that give information on endgame (W13 and high tier PvP) advise the use of magnetic torpedoes.

They don’t seem to appear in your guide at all.

Could you tell us something about that?

**Comment by guroteske** [comment]
magtorps sacrifice a fairly substantial amount of damage and reload speed, with the homing effect being relatively weak. when playing on manual (which this guide assumes), the benefits of mags are relatively minor compared to conventional torpedoes and almost never worth bringing

on auto, meanwhile, all torpedoes will suffer a massive hit to efficacy, homing or not, to the point where you're better off running gunnery-focused ships unless the ship in question provides enough benefit to justify how much weaker their torpedoes will be (e.g. yukikaze)

**Comment by Fishman465** [comment]
And the only variant that comes close (still less damage) to the two golden normal torps (T3 Rainbow quint mag) is no longer available, and even then its stats lend itself to to ships with weak TRP but higher efficiencies, not one of the usual torp suspects.

**Comment by Fishman465** [comment]
Well the T3/Rainbow Mag torps are now a gear lab item, but the points stand still especially with the mats required for it.
