### ISSUE TITLE
The links in the Table of contents (that link to DD, CL, CA, etc.) don't work in Waterfox Classic 2020.09 64-bit

### ISSUE THREAD

**Issue by Bu11etmagnet** [YourWaifuIsShip/Azur-Lane-Guides#39]
Clicking on e.g. DD appends "#dd--1" to the URL in the address bar, but it doesn't jump to the DD section.
Links also don't work in Pale Moon 28.14.2
Links work in Chromium Version 85.0.4156.0 (Official Build) (64-bit)

Links work in Waterfox Classic for https://github.com/YourWaifuIsShip/Azur-Lane-Guides/blob/52d736d1a82556ce6d45bac3ca5552a437b2df71/AL%20Tier%20Guide.md

**Comment by splashsky** [comment]
I don't believe this a repo issue. You could take a look and see if the links are written in the same manner as the ones on the page you linked to, but afaik Waterfox Classic has had a significant number of issues with this lately.

**Comment by YourWaifuIsShip** [comment]
Thanks for answering, Splashsky!
With apologies for the hiatus-caused exceptionally long delay, I'd have to admit I wouldn't have known how fix it even had I been around, save for a frantic Google search and crossed fingers.
Is the issue solved, now?

**Comment by Bu11etmagnet** [comment]
Seems to be working; it's unclear what the problem was (especially since right-clicking on the link and selecting "Open link in a new tab" would open the same page and scroll to the correct place).
