### ISSUE TITLE
Balance tweak changes

### ISSUE THREAD

**Issue by Fishman465** [YourWaifuIsShip/Azur-Lane-Guides#40]
Just a reminder that some ships did get buffs, some enough for a reconsideration for some. Once I get on my PC, I'll put a precise list of changes

**Comment by YourWaifuIsShip** [comment]
Aye aye, but no need to worry really; unless someone goes and deletes the pin in #al-help I'll be good~

**Comment by Fishman465** [comment]
Not sure if that pin is 100% accurate (doesn't cover some of the efficiency buffs some ships got or Graf Zepplin's raw stat boosts); though the wiki has all the updated values (I know as I was among those updating it)

That and EN got the revamped Giant Hunter skill wrong (Graf Spee is not needed)

**Comment by YourWaifuIsShip** [comment]
Ah, right, EN. Can't trust it. Well, I'll be waiting for the details~

**Comment by Fishman465** [comment]
The pinned image isn't 100% wrong, but I'll say what's actually not mentioned and what the actual values are if it's wrong.

Takao-class: They got it right with the normal barrages firing in 4 shots and the first trigger giving a 10% evade rate boost for the rest of the battle.  I don't think it'll change too much but it's a plus for their fans.

Shoukaku: They don't mention the real change to Crane's Protection is that the damage buff now affects the airstrike of Shou's that triggered it when it didn't before, which was an annoying quirk IIRC.

Zuikaku: They got the change right. Might be a real boost (Not like one'd mix too much with IN ships)

Taihou: They're correct in how one effect became 100% and the remaining two drop from 30% to 25%.

Giant Hunter (Ajax Re, Achillies Re, Exeter Re): Only things they got wrong was needing Graf Spee for the effects, which are otherwise right. That and not listing Ajax or Achilles. Dunno about Exeter, but it's a real buff to the CLs IMO.

Victorious: They're right, though not sure if an "+10% (at lv10) Damage to BBs by ally CVs and CVL" 2nd effect is much of a change.

Prince of Wales: Also right in its effects and values. A pretty big boost in the self buffs are stronger and being with an otherwise half+ eagle Union fleet is mutually rewarding.

Javelin: Also correct, but it doesn't mention how her torpedo efficiency was boosted by 10, putting hers closer to I think Laffey's.

South Dakota: The pic is correct.

Massachusetts: Pic is correct, Gotta say the ability to not be 100% forced into SHS and Big Mammie now including her makes her more flexible.

Reno: Her Main Gun and Torpedo Efficiency were increased by 5 each, and the 35% crit boost rte only applies to the main gun alone, but otherwise correct.

Graf Zeppelin: Her Aviation and Reload got increased by 5/5 (lv1), 23/11(lv100), and 23/12 (Lv120). She is able to use Torpedo bombers in her Dive Bomber slot. I feel this is another big buff as it makes her equipment more flexible in a number of ways. Everything on the pic is correct through.

**Comment by Fishman465** [comment]
Looking at it, I've done a pull to correct what few issues there are and is Prince of Wales' buffs not enough to have her added?

**Comment by YourWaifuIsShip** [comment]
No, I just haven't gotten around to adding her back in yet~

**Comment by Fishman465** [comment]
Here's some differences of Wave 2 Muse ships at a glance (stuff like barrage details and such need looking into)

Roon Mu: Same stats/eff the original basically (i.e. not so strong at first but pretty strong at lv100/max enhance), and her kit is much better with an offensive focus (her shield skill replaces two defensive one with red damaging ones) and has a special barrage skill. I think she's stronger than her original version. Only downside: No tech points (not much of a down side with the recent event is enough to max that out without her)

Taihou Mu: Roughly similar stats, same eff, bu her kit is very consistent with a clear offensive focus. Her first skill adds a plane barrage (which if her HP is above 45%, it'll be stronger if costing 200 HP). The other has her get more AVI with other Muse ships and when damaged below 35% HP, will counter attack with a HP draining barrage and hastens her next normal one. I'd say similar strength but different roles.

Le Malin Mu: Similar stats, same eff, but her kit is different. First still is kind of quirky as it stops her for 3s every 20s to launch a special airwing which has a 50% chance to heal her a bit. Her second boosts her FP and gives a smaller boost (for the rest of the battle) for each enemy sunk (up to 3 times), reduces damage she takes by a bit, and heals all DDs a bit in the same fleet every 25s. Quirky but maintains full effectiveness for longer than Original (despite her having such issues in the event)

Albacore Mu: Stats/Eff is basically OG Albacore -1 (due to the rarity downgrade). She loses the DD/CL/CV damage boost, but gains extra Oxygen while her special barrage launches 70% armor breaking torps and when she retreats fires 70% burn inflicting ones. Not quite a "minus one" overall

Baltimore Mu:  Stats/Eff basically minus one save the AA Gun eff which is unchanged. Her first skill has a chance to temporarily change her ammo type to a special HE type (game says AP) with balanced but leaning towards Heavy modifiers. (at lv10 it/s 100/110/120). The other skill boosts her evasion and all vanguard ships in the same fleet's AA if there's a CV, CVL, or Muse ship in the same fleet. I'd say she's closer to a Minus one, but has her niches.

Dido Mu: More of an AA focus compared to her normal version (hence her AA is comparable to regular San Diego) while only suffering a small drop in FP and MG eff (which went to her AA gun eff). Her yellow skill gives a stacking with every 2 sunk enemies (up to 3 times) 10% AA buff and an evasion boost for the first 60s. Her blue skill has different effects depending on if she's the only ship in the vanguard at the start of the battle. If she is, fires a barrage every 20s while boosting her AA. If not, fires a possibly different barrage every 20s while boosting the vanguard's speed and accuracy. Could work as a more surface combat able AA carry, assuming one doesn't have the big 3 in that area (Reno, Seattle, Super Sandy) or insistent on using maids.

Illustrious Mu: Her eff is a more offensive (bit more Avi, Eff is 125/125/135 compared to the original's 135/135/110), though still with the 6F/3TB setup. Has as special airstrike and a random buff or debuff effect when her airstrikes are ready. I'd say a mildly more offensive ACV boat, but with her other skill being random, I'm not sure it's enough to earn her merit on the list.

Tashkent Mu: Lower FP/AA, but higher Torp and slightly higher RLD but maintains the same efficiencies. Her red skill still has the Not!Nav summon but it also fires a special barrage and when the fairy hits an enemy 10 times, the enemy will get a "+5 Aviation damage taken" debuff. And yellow skill boosts her FP for the first 3 battles and her AA for the rest. Unless there's something I'm missing, I'd say she's weaker than the original. Had they adjusted her eff to reflect the heavier Torp focus, she'd stand out more as a different variant.
