### ISSUE TITLE
Missing gun in DD gun spreadsheet?

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#43]
I don’t know how much saying you have in the creation of the gun spreadsheets.

In my opinion the 138.6mm model 1927 should be added to it.

From my experience it at the very least beats the twin 120mm QF.

It’s not farmable right now, but this goes for guns on that sheet as well.

**Comment by Fishman465** [comment]
He has nothing to do with equipment stuff.
