### ISSUE TITLE
wrong data and possibly assesment of Akagi muse

### ISSUE THREAD

**Issue by milothefirst** [YourWaifuIsShip/Azur-Lane-Guides#44]
when her barrage is max level, it launches 6 planes not 3 as stated, for both DB and TB. also the torpedo bombers are equivalent to:
2 x Sakura Aerial T3 at +10  (240 base damage) x 6 planes (seemingly they are Nakajima B5N Type 97, even though as a gear they can only reach up to +7) at 100% efficiency and modified by 100% of Aviation stat. 
only the dive bomber barrage get modified by 80% aviation stat, as all dive bombers do

**Comment by YourWaifuIsShip** [comment]
https://azurlane.koumakan.jp/User:Riceist/BarrageDatamine
According to this, you are correct. Will correct it soon.

**Comment by YourWaifuIsShip** [comment]
Corrected, thanks for pointing it out.
