### ISSUE TITLE
USS Indianapolis appears missing

### ISSUE THREAD

**Issue by ralinchan** [YourWaifuIsShip/Azur-Lane-Guides#45]
It seems that Indianapolis is missing from the guide.

Appearing twice in Portland's description seems to be the only time I can locate her

The explanation link for Izumo being missing also goes to a 404

**Comment by EndlingGER** [comment]
Indianapolis is not missing so much as she is not good enough to be in. Wichita and Chicago can outgun her. Portland and Houston can outlast her. And these are only the competitors in her “league”.

**Comment by ralinchan** [comment]
Appreciate the response. Was linked directly from the subreddit so was trying to use this as a guide as a blind newb
