### ISSUE TITLE
Confusion about Massachusetts’ first skill.

### ISSUE THREAD

**Issue by EndlingGER** [YourWaifuIsShip/Azur-Lane-Guides#46]
Both the wiki and the ingame description make it sound like Massachusetts herself is included in the 3 ships needed for maximum stacks.

Though in your list it says she is not included.

**Comment by J-Aquila** [comment]
That discrepancy looks like a relic from the balance changes introduced with OpSi. When Massa was introduced in *Iris of Light and Dark*, it was 3 other ships (she did not count for the skill). When the Dec.2020 balance changes came around, the first skill was changed to needing 3 USS CA/BBs, counting her as the first one (so really, only needing two more ships).

**Comment by YourWaifuIsShip** [comment]
Updated her skill description, thank you! Didn't notice it kept the old text, now it should be clear she counts for it too.
